### ISSUE TITLE
Release folder

### ISSUE THREAD

**Issue by KalenBerry** [haiderriazkhan/CANDLE-J#3]
From the ReadMe. "In the top header of this repository, click release. Depending on your operating system, either download the MacOSX.zip,Windows.zip or Linux.tar.gz file from the listing."

I'm sorry if I am missing something obvious, but I can not find a folder named release or another option on github named that.

**Comment by haiderriazkhan** [comment]
Here is a picture. The `release` button can be seen in this jpeg nestled between `branch` and `contributor`. There is a 1 before it to signify that there is only one release so far.

<img width="1040" alt="screen shot 2015-12-15 at 12 32 18 pm" src="https://cloud.githubusercontent.com/assets/6717554/11818378/16783e76-a328-11e5-9875-f54e491fd8b2.png">
